<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.2.1" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Catalog\Gapotchenko.FX.Text\Gapotchenko.FX.Text.csproj" />
    <ProjectReference Include="..\..\..\Catalog\Linq\Gapotchenko.FX.Linq.Async\Gapotchenko.FX.Linq.Async.csproj" />
    <ProjectReference Include="..\..\..\Catalog\Linq\Gapotchenko.FX.Linq\Gapotchenko.FX.Linq.csproj" />
  </ItemGroup>

</Project>
