//
//  This CSharp output file generated by Gardens Point LEX
//  Gardens Point LEX (GPLEX) is Copyright (c) John Gough, QUT 2006-2014.
//  Output produced by GPLEX is the property of the user.
//  See accompanying file GPLEXcopyright.rtf.
//
//  GPLEX Version:  1.2.2
//  GPLEX input file <Serialization\Dot.lex - 15.12.2021 18:12:29>
//  GPLEX frame file <SERIALIZATION\DOTLEXFRAME.CS>
//
//  Option settings: unicode, parser, minimize
//  Option settings: classes, compressMap, compressNext, persistBuffer, embedbuffers
//  Fallback code page: Target machine default
//

//
// Revised backup code
// Version 1.2.1 of 24-June-2013
//
//
#define BACKUP
#define PERSIST

using System;
using System.IO;
using System.Text;
using System.Globalization;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;

using Gapotchenko.FX.Data.Dot.ParserToolkit;

namespace Gapotchenko.FX.Data.Dot.Serialization
{
    /// <summary>
    /// Summary Canonical example of GPLEX automaton
    /// </summary>

    // If the compiler can't find the scanner base class maybe you
    // need to run GPPG with the /gplex option, or GPLEX with /noparser
     internal sealed partial class DotLex : ScanBase, IDisposable
    {
        ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
        
        /// <summary>
        /// The input buffer for this scanner.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ScanBuff Buffer => buffer;

        const int maxAccept = 37;
        const int initial = 38;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;
        const int QSTRING = 1;
        const int HTML = 2;
        const int LINECOMMENT = 3;
        const int MLINECOMMENT = 4;

#region user code
int nesting = 0;
  
    internal void LoadYylVal() {
        yylval = yytext; // tokTxt
    }
#endregion user code

        int state;
        int currentStart = startState[0];
        int code;      // last code read
        int cCol;      // column number of code
        int lNum;      // current line number
        //
        // The following instance variables are used, among other
        // things, for constructing the yylloc location objects.
        //
        int tokPos;        // buffer position at start of token
        int tokCol;        // zero-based column number at start of token
        int tokLin;        // line number at start of token
        int tokEPos;       // buffer position at end of token
        int tokECol;       // column number at end of token
        int tokELin;       // line number at end of token
        string? tokTxt;     // lazily constructed text of token
#if STACK          
        Stack<int> scStack = new Stack<int>();
#endif // STACK

#region ScannerTables
    struct Table {
        public int min; public int rng; public int dflt;
        public sbyte[]? nxt;
        public Table(int m, int x, int d, sbyte[]? n) {
            min = m; rng = x; dflt = d; nxt = n;
        }
    };

    static int[] startState = new int[] {38, 40, 41, 42, 43, 0};

#region CompressedCharacterMap
    //
    // There are 23 equivalence classes
    // There are 2 character sequence regions
    // There are 1 tables, 128 entries
    // There are 1 runs, 0 singletons
    // Decision tree depth is 1
    //
    static sbyte[] mapC0 = new sbyte[128] {
/*     '\0' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 17, 20, 20, 21, 0, 0, 
/*   '\x10' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*   '\x20' */ 20, 0, 6, 16, 0, 0, 0, 0, 0, 0, 19, 0, 11, 1, 5, 18, 
/*      '0' */ 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 13, 12, 15, 14, 2, 0, 
/*      '@' */ 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
/*      'P' */ 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 7, 22, 8, 0, 3, 
/*      '`' */ 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
/*      'p' */ 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 0, 10, 0, 0 };

    static sbyte MapC(int code)
    { // '\0' <= code <= '\U0010FFFF'
      if (code < 128) // '\0' <= code <= '\x7F'
        return mapC0[code - 0];
      else // '\x80' <= code <= '\U0010FFFF'
        return (sbyte)3;
    }
#endregion

    static Table[] NxS = new Table[44] {
/* NxS[   0] */ new Table(0, 0, 0, null),
/* NxS[   1] */ new Table(0, 0, -1, null),
/* NxS[   2] */ new Table(1, 5, -1, new sbyte[] {23, 24, -1, 4, 39}),
/* NxS[   3] */ new Table(3, 2, -1, new sbyte[] {3, 3}),
/* NxS[   4] */ new Table(3, 3, -1, new sbyte[] {22, 4, 21}),
/* NxS[   5] */ new Table(4, 1, -1, new sbyte[] {21}),
/* NxS[   6] */ new Table(0, 0, -1, null),
/* NxS[   7] */ new Table(0, 0, -1, null),
/* NxS[   8] */ new Table(0, 0, -1, null),
/* NxS[   9] */ new Table(0, 0, -1, null),
/* NxS[  10] */ new Table(0, 0, -1, null),
/* NxS[  11] */ new Table(0, 0, -1, null),
/* NxS[  12] */ new Table(0, 0, -1, null),
/* NxS[  13] */ new Table(0, 0, -1, null),
/* NxS[  14] */ new Table(0, 0, -1, null),
/* NxS[  15] */ new Table(0, 0, -1, null),
/* NxS[  16] */ new Table(0, 0, -1, null),
/* NxS[  17] */ new Table(17, 5, -1, new sbyte[] {17, -1, -1, 17, 17}),
/* NxS[  18] */ new Table(18, 2, -1, new sbyte[] {19, 20}),
/* NxS[  19] */ new Table(0, 0, -1, null),
/* NxS[  20] */ new Table(0, 0, -1, null),
/* NxS[  21] */ new Table(3, 3, -1, new sbyte[] {22, 21, 22}),
/* NxS[  22] */ new Table(0, 0, -1, null),
/* NxS[  23] */ new Table(0, 0, -1, null),
/* NxS[  24] */ new Table(0, 0, -1, null),
/* NxS[  25] */ new Table(22, 8, 25, new sbyte[] {-1, 25, 25, 25, 25, 25, 
          25, -1}),
/* NxS[  26] */ new Table(0, 0, -1, null),
/* NxS[  27] */ new Table(22, 8, -1, new sbyte[] {29, -1, -1, -1, -1, -1, 
          -1, 28}),
/* NxS[  28] */ new Table(0, 0, -1, null),
/* NxS[  29] */ new Table(0, 0, -1, null),
/* NxS[  30] */ new Table(0, 0, -1, null),
/* NxS[  31] */ new Table(0, 0, -1, null),
/* NxS[  32] */ new Table(0, 0, -1, null),
/* NxS[  33] */ new Table(0, 0, -1, null),
/* NxS[  34] */ new Table(0, 0, -1, null),
/* NxS[  35] */ new Table(0, 0, -1, null),
/* NxS[  36] */ new Table(18, 1, -1, new sbyte[] {37}),
/* NxS[  37] */ new Table(0, 0, -1, null),
/* NxS[  38] */ new Table(22, 21, 17, new sbyte[] {1, 1, 2, 1, 3, 4, 
          5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1}),
/* NxS[  39] */ new Table(4, 1, -1, new sbyte[] {21}),
/* NxS[  40] */ new Table(22, 8, 25, new sbyte[] {27, 25, 25, 25, 25, 25, 
          25, 26}),
/* NxS[  41] */ new Table(15, 11, 30, new sbyte[] {32, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 31}),
/* NxS[  42] */ new Table(17, 5, 33, new sbyte[] {34, 33, 33, 33, 34}),
/* NxS[  43] */ new Table(19, 1, 35, new sbyte[] {36}),
    };

int NextState() {
    if (code == ScanBuff.EndOfFile)
        return eofNum;
    else
        unchecked {
            int rslt;
            int idx = MapC(code) - NxS[state].min;
            if (idx < 0) idx += 23;
            if ((uint)idx >= (uint)NxS[state].rng) rslt = NxS[state].dflt;
            else rslt = NxS[state].nxt![idx];
            return rslt;
        }
}

#endregion


#if BACKUP
        // ==============================================================
        // == Nested struct used for backup in automata that do backup ==
        // ==============================================================

        struct Context // class used for automaton backup.
        {
            public int bPos;
            public int rPos; // scanner.readPos saved value
            public int cCol;
            public int lNum; // Need this in case of backup over EOL.
            public int state;
            public int cChr;
        }
        
        Context ctx = new Context();
#endif // BACKUP

        // ==============================================================
        // ==== Nested struct to support input switching in scanners ====
        // ==============================================================

		struct BufferContext {
            internal ScanBuff buffSv;
			internal int chrSv;
			internal int cColSv;
			internal int lNumSv;
		}

        // ==============================================================
        // ===== Private methods to save and restore buffer contexts ====
        // ==============================================================

        /// <summary>
        /// This method creates a buffer context record from
        /// the current buffer object, together with some
        /// scanner state values. 
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        BufferContext MkBuffCtx()
		{
			BufferContext rslt;
			rslt.buffSv = this.buffer;
			rslt.chrSv = this.code;
			rslt.cColSv = this.cCol;
			rslt.lNumSv = this.lNum;
			return rslt;
		}

        /// <summary>
        /// This method restores the buffer value and allied
        /// scanner state from the given context record value.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void RestoreBuffCtx(BufferContext value)
		{
			this.buffer = value.buffSv;
			this.code = value.chrSv;
			this.cCol = value.cColSv;
			this.lNum = value.lNumSv;
        } 
        // =================== End Nested classes =======================

#if !NOFILES
     internal DotLex(TextReader reader)
        {
            this.buffer = ScanBuff.GetBuffer(reader);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
#endif // !NOFILES

        int readPos;

        void GetCode()
        {
            if (code == '\n')  // This needs to be fixed for other conventions
                               // i.e. [\r\n\205\u2028\u2029]
            { 
                cCol = -1;
                lNum++;
            }
            readPos = buffer.Pos;

            // Now read new codepoint.
            code = buffer.Read();
            if (code > ScanBuff.EndOfFile)
            {
#if (!BYTEMODE)
                if (code >= 0xD800 && code <= 0xDBFF)
                {
                    int next = buffer.Read();
                    if (next < 0xDC00 || next > 0xDFFF)
                        code = ScanBuff.UnicodeReplacementChar;
                    else
                        code = (0x10000 + ((code & 0x3FF) << 10) + (next & 0x3FF));
                }
#endif
                cCol++;
            }
        }

        void MarkToken()
        {
#if (!PERSIST)
            buffer.Mark();
#endif
            tokPos = readPos;
            tokLin = lNum;
            tokCol = cCol;
        }
        
        void MarkEnd()
        {
            tokTxt = null;
            tokEPos = readPos;
            tokELin = lNum;
            tokECol = cCol;
        }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int Peek()
        {
            int rslt, codeSv = code, cColSv = cCol, lNumSv = lNum, bPosSv = buffer.Pos;
            GetCode(); rslt = code;
            lNum = lNumSv; cCol = cColSv; code = codeSv; buffer.Pos = bPosSv;
            return rslt;
        }

        // ======== AbstractScanner<> Implementation =========

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public override int yylex() =>
            Scan();
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yypos { get { return tokPos; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yyline { get { return tokLin; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yycol { get { return tokCol; } }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yytext")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yytext")]
        public string yytext
        {
            get 
            {
                if (tokTxt == null) 
                    tokTxt = buffer.GetString(tokPos, tokEPos);
                return tokTxt;
            }
        }

        /// <summary>
        /// Discards all but the first "n" codepoints in the recognized pattern.
        /// Resets the buffer position so that only n codepoints have been consumed;
        /// yytext is also re-evaluated. 
        /// </summary>
        /// <param name="n">The number of codepoints to consume</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void yyless(int n)
        {
            buffer.Pos = tokPos;
            // Must read at least one char, so set before start.
            cCol = tokCol - 1; 
            GetCode();
            // Now ensure that line counting is correct.
            lNum = tokLin;
            // And count the rest of the text.
            for (int i = 0; i < n; i++) GetCode();
            MarkEnd();
        }
       
        //
        //  It would be nice to count backward in the text
        //  but it does not seem possible to re-establish
        //  the correct column counts except by going forward.
        //
        /// <summary>
        /// Removes the last "n" code points from the pattern.
        /// </summary>
        /// <param name="n">The number to remove</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void _yytrunc(int n) { yyless(yyleng - n); }
        
        //
        // This is painful, but we no longer count
        // codepoints.  For the overwhelming majority 
        // of cases the single line code is fast, for
        // the others, well, at least it is all in the
        // buffer so no files are touched. Note that we
        // can't use (tokEPos - tokPos) because of the
        // possibility of surrogate pairs in the token.
        //
        /// <summary>
        /// The length of the pattern in codepoints (not the same as 
        /// string-length if the pattern contains any surrogate pairs).
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yyleng")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yyleng")]
        public int yyleng
        {
            get {
                if (tokELin == tokLin)
                    return tokECol - tokCol;
                else
#if BYTEMODE
                    return tokEPos - tokPos;
#else
                {
                    int ch;
                    int count = 0;
                    int save = buffer.Pos;
                    buffer.Pos = tokPos;
                    do {
                        ch = buffer.Read();
                        if (!char.IsHighSurrogate((char)ch)) count++;
                    } while (buffer.Pos < tokEPos && ch != ScanBuff.EndOfFile);
                    buffer.Pos = save;
                    return count;
                }
#endif // BYTEMODE
            }
        }
        
        // ============ methods available in actions ==============

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int YY_START {
            get { return currentScOrd; }
            set { currentScOrd = value; 
                  currentStart = startState[value]; 
            } 
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void BEGIN(int next) {
            currentScOrd = next;
            currentStart = startState[next];
        }

        // ============== The main tokenizer code =================

        int Scan() {
            try {
                for (; ; ) {
                    int next;              // next state to enter
#if LEFTANCHORS
                    for (;;) {
                        // Discard characters that do not start any pattern.
                        // Must check the left anchor condition after *every* GetCode!
                        state = ((cCol == 0) ? anchorState[currentScOrd] : currentStart);
                        if ((next = NextState()) != goStart) break; // LOOP EXIT HERE...
                        GetCode();
                    }
                    
#else // !LEFTANCHORS
                    state = currentStart;
                    while ((next = NextState()) == goStart) {
                        // At this point, the current character has no
                        // transition from the current state.  We discard 
                        // the "no-match" char.   In traditional LEX such 
                        // characters are echoed to the console.
                        GetCode();
                    }
#endif // LEFTANCHORS                    
                    // At last, a valid transition ...    
                    MarkToken();
                    state = next;
                    GetCode();                    
#if BACKUP
                    bool contextSaved = false;
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                        if (state <= maxAccept && next > maxAccept) { // need to prepare backup data
                            // Store data for the *latest* accept state that was found.
                            SaveStateAndPos( ref ctx );
                            contextSaved = true;
                        }
                        state = next;
                        GetCode();
                    }
                    if (state > maxAccept && contextSaved)
                        RestoreStateAndPos( ref ctx );
#else  // BACKUP
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                         state = next;
                         GetCode();
                    }
#endif // BACKUP
                    if (state <= maxAccept) {
                        MarkEnd();
#region ActionSwitch
#pragma warning disable 162, 1522
    switch (state)
    {
        case eofNum:
            if (yywrap())
                return (int)Tokens.EOF;
            break;
        case 1:
        case 2:
        case 5:
        case 18:
RaiseUnexpectedCharError(yytext);
            break;
        case 3:
        case 4:
        case 21:
        case 22:
return (int) MkId(yytext);
            break;
        case 6:
BEGIN(QSTRING); BuilderInit(); BuilderAppend();
            break;
        case 7:
return (int)DotTokenKind.ListStart;
            break;
        case 8:
return (int)DotTokenKind.ListEnd;
            break;
        case 9:
return (int)DotTokenKind.ScopeStart;
            break;
        case 10:
return (int)DotTokenKind.ScopeEnd;
            break;
        case 11:
return (int)DotTokenKind.Comma;
            break;
        case 12:
return (int)DotTokenKind.Semicolon;
            break;
        case 13:
return (int)DotTokenKind.Colon;
            break;
        case 14:
return (int)DotTokenKind.Equal;
            break;
        case 15:
BEGIN(HTML); nesting = 1; BuilderInit(); BuilderAppend();
            break;
        case 16:
BEGIN(LINECOMMENT); BuilderInit(); BuilderAppend();
            break;
        case 17:
return (int)DotTokenKind.Whitespace;
            break;
        case 19:
BEGIN(LINECOMMENT); BuilderInit(); BuilderAppend();
            break;
        case 20:
BEGIN(MLINECOMMENT); BuilderInit(); BuilderAppend();
            break;
        case 23:
return (int) DotTokenKind.Arrow;
            break;
        case 24:
return (int) DotTokenKind.Arrow;
            break;
        case 25:
        case 27:
BuilderAppend();
            break;
        case 26:
BEGIN(INITIAL); BuilderAppend(); tokTxt = BuilderBuild(); return (int)DotTokenKind.Id;
            break;
        case 28:
BuilderAppend();
            break;
        case 29:
BuilderAppend();
            break;
        case 30:
BuilderAppend();
            break;
        case 31:
nesting--; 
                     BuilderAppend();
                     if (nesting == 0) {
                       BEGIN(INITIAL);
                       tokTxt = BuilderBuild();
                       return (int)DotTokenKind.Id;
                     }
            break;
        case 32:
nesting++; 
                     BuilderAppend();
            break;
        case 33:
BuilderAppend();
            break;
        case 34:
_yytrunc(1); tokTxt = BuilderBuild(); BEGIN(INITIAL); return (int)DotTokenKind.Comment;
            break;
        case 35:
        case 36:
BuilderAppend();
            break;
        case 37:
BuilderAppend(); tokTxt = BuilderBuild(); BEGIN(INITIAL); return (int)DotTokenKind.MultilineComment;
            break;
        default:
            break;
    }
#pragma warning restore 162, 1522
#endregion
                    }
                }
            } // end try
            finally {
// User-specified epilog to scan()
/* Epilog from LEX file */
    LoadYylVal();
// End, user-specified epilog
            } // end finally
        }

#if BACKUP
        void SaveStateAndPos(ref Context ctx) {
            ctx.bPos  = buffer.Pos;
            ctx.rPos  = readPos;
            ctx.cCol  = cCol;
            ctx.lNum  = lNum;
            ctx.state = state;
            ctx.cChr  = code;
        }

        void RestoreStateAndPos(ref Context ctx) {
            buffer.Pos = ctx.bPos;
            readPos = ctx.rPos;
            cCol  = ctx.cCol;
            lNum  = ctx.lNum;
            state = ctx.state;
            code  = ctx.cChr;
        }
#endif  // BACKUP

        // ============= End of the tokenizer code ================

#if STACK        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void yy_clear_stack() { scStack.Clear(); }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int yy_top_state() { return scStack.Peek(); }
        
        internal void yy_push_state(int state)
        {
            scStack.Push(currentScOrd);
            BEGIN(state);
        }
        
        internal void yy_pop_state()
        {
            // Protect against input errors that pop too far ...
            if (scStack.Count > 0) {
				int newSc = scStack.Pop();
				BEGIN(newSc);
            } // Otherwise leave stack unchanged.
        }
 #endif // STACK

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void ECHO() { Console.Out.Write(yytext); }
        
        public void Dispose()
        {
            if (buffer is not null)
            {
                buffer.Dispose();
                buffer = null!;
            }
        }

        } // end class DotLex

} // end namespace
