<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Reference Condition=" '$(TargetFrameworkIdentifier)' == '.NETFramework' AND $([MSBuild]::VersionGreaterThanOrEquals($(TargetFrameworkVersion), '4.7.2')) " Include="System.IO.Compression" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Catalog\Data\Archives\Gapotchenko.FX.Data.Archives.Zip\Gapotchenko.FX.Data.Archives.Zip.csproj" />
    <ProjectReference Include="..\..\..\IO\Gapotchenko.FX.IO.Vfs.Tests\Gapotchenko.FX.IO.Vfs.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>

</Project>
