//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gapotchenko.FX.Security.Cryptography.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gapotchenko.FX.Security.Cryptography.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified initialization vector (IV) does not match the block size for {0} algorithm..
        /// </summary>
        internal static string IVDoesNotMatchXAlgorithmBlockSize {
            get {
                return ResourceManager.GetString("IVDoesNotMatchXAlgorithmBlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified key is a known semi-weak key for {0} algorithm and cannot be used..
        /// </summary>
        internal static string SpecifiedKeyIsKnownSemiWeakForXAlgorithm {
            get {
                return ResourceManager.GetString("SpecifiedKeyIsKnownSemiWeakForXAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified key is a known weak key for {0} algorithm and cannot be used..
        /// </summary>
        internal static string SpecifiedKeyIsKnownWeakForXAlgorithm {
            get {
                return ResourceManager.GetString("SpecifiedKeyIsKnownWeakForXAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified key is not a valid size for {0} algorithm..
        /// </summary>
        internal static string SpecifiedKeyIsNotValidSizeForXAlgorithm {
            get {
                return ResourceManager.GetString("SpecifiedKeyIsNotValidSizeForXAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} algorithm cannot be used because it is not FIPS-compliant..
        /// </summary>
        internal static string XAlgorithmCannotBeUsedDueFips {
            get {
                return ResourceManager.GetString("XAlgorithmCannotBeUsedDueFips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} algorithm does not support initialization vector..
        /// </summary>
        internal static string XAlgorithmDoesNotSupportIV {
            get {
                return ResourceManager.GetString("XAlgorithmDoesNotSupportIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} algorithm does not support modes other than {1}..
        /// </summary>
        internal static string XAlgorithmDoesNotSupportModesExceptY {
            get {
                return ResourceManager.GetString("XAlgorithmDoesNotSupportModesExceptY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} algorithm does not support paddings other than {1}..
        /// </summary>
        internal static string XAlgorithmDoesNotSupportPaddingsExceptY {
            get {
                return ResourceManager.GetString("XAlgorithmDoesNotSupportPaddingsExceptY", resourceCulture);
            }
        }
    }
}
