<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Gapotchenko.FX.Diagnostics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <CommonlyUsedPart Include="Gapotchenko.FX.Diagnostics.CommandShell" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Catalog\Diagnostics\Gapotchenko.FX.Diagnostics.CommandLine\Gapotchenko.FX.Diagnostics.CommandLine.csproj" />
  </ItemGroup>

</Project>
