<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageTag Include="security;cryptography;fips;rc4;md5;des;3des" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Security.Cryptography" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Gapotchenko.FX.Numerics\Gapotchenko.FX.Numerics.csproj" />
    <ProjectReference Include="..\..\Gapotchenko.FX\Gapotchenko.FX.csproj" />
  </ItemGroup>

</Project>
