<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageTag Include="security;cryptography;fips;rc4;des" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Security.Cryptography" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\Gapotchenko.FX\Gapotchenko.FX.csproj" />
  </ItemGroup>

</Project>
