<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!--<Prefer32Bit>true</Prefer32Bit>-->
    <RootNamespace>Gapotchenko.FX.Runtime.CompilerServices.Harness</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  
  <PropertyGroup>
    <NoWarn>$(NoWarn),CS0162</NoWarn>
    <AnalysisMode>none</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gapotchenko.FX.Runtime.CompilerServices.Intrinsics\Gapotchenko.FX.Runtime.CompilerServices.Intrinsics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>

</Project>
